[map]
# 地图文件路径
map_data_file = N32E119.npz
# 地图分辨率
map_resolution = 30

[env]
# 任务成功半径 m
task_success_radius = 51
# 局部观测半径 m
uav_obs_radius = 2000
# 飞行速度 m/s 50
uav_velocity_value = 50
# 无人机长度
uav_length = 3.05
#无人机初始高度
uva_init_height = 80
# map输出维度
map_output_dimension = 1000

# 碰撞安全距离
coll_safe_dis = 10
# 目标和武器的距离
dis_target_weapon = 50
# 目标和UAV的最小距离
dis_target_uav_min = 120
# 目标和UAV的最大距离
dis_target_uav_max = 150
# 诱饵机数量
n_decoy_uavs = 0
# 任务机数量
n_task_uavs = 1



[reward]
# 引诱的安全距离
decoy_safe_dis = 50
# UAV碰撞时的惩罚(初始值40）
uav_coll_penalty = 10
# 执行动作的惩罚
step_penalty = 1
# 引诱成功的奖励20
decoy_success_reward = 0
# 引诱距离奖励的比例系数1
decoy_dis_reward_index = 0
# 任务成功的奖励(初始值是100）
task_success_reward = 100
# 被山体遮挡的奖励(初始值是5）
mountain_shading_reward = 0
# 任务距离奖励的比例系数(初始值是0.04）
task_dis_reward_index = 0.04

[constraints]
# 最高可飞行高度
max_available_height = 3000
# 最低可飞行高度
min_available_height = 0

